name: prueba

on:
  push:
    branches: feature
  pull_request:

jobs:
  build:
    runs-on: self-hosted
    steps:      
      - name: Comparar variables de entorno
        shell: powershell
        env:
          VAR1: ${{ secrets.DEV_TOKEN }}
        run: |
          if ($env:VAR1 -ceq $env:LOCAL_DEV_TOKEN) {
            Write-Output "Los tokens coinciden"
          } else {
            Write-Output "Los tokens no coinciden"
          }
