name: prueba

on:
  push:
    branches: main
  pull_request:

jobs:
  build:
    runs-on: self-hosted
    steps:      
      - name: Comparar variables de entorno
        shell: bash
        env:
          VAR1: ${{ secrets.DEV_TOKEN }}
          VAR2: ${{ LOCAL_DEV_TOKEN }}
        run: |
          if [ "$VAR1" = "$VAR2" ]; then
            echo "Los tokens coinciden"
          else
            echo "Los tokens no coinciden"
          fi


